apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hvxrjhyol-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:e5493cc893f73ba50e1cf1efc5799059e0e4d7ba@sha256:14d3b7f7c96d1ee116401345b40dcf7f681661cdda38c0992d506ed198535654
          name: container-image
