apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hvxrjhyol-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hvxrjhyol-go 
  name: hvxrjhyol-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hvxrjhyol-go 
